In [1]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as mtp  

In [2]:
data_set= pd.read_csv('iris.csv') 
data_set

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
x= data_set.iloc[:,[2,3]].values
y= data_set.iloc[:,4].values
x

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [4]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
x_train

array([[ 2.50967307e-01,  3.96171883e-01],
       [ 1.37235899e-01,  1.75297293e-03],
       [ 9.90221459e-01,  1.18500970e+00],
       [-1.39813811e+00, -1.31297673e+00],
       [ 7.62758643e-01,  1.44795564e+00],
       [-1.22754100e+00, -7.87084847e-01],
       [-1.28440670e+00, -1.31297673e+00],
       [-1.47092621e-01, -2.61192967e-01],
       [ 9.90221459e-01,  7.90590793e-01],
       [ 1.10395287e+00,  1.71090158e+00],
       [ 7.05892939e-01,  3.96171883e-01],
       [ 1.16081857e+00,  7.90590793e-01],
       [ 8.03701950e-02, -1.29719997e-01],
       [ 1.33141568e+00,  1.44795564e+00],
       [ 5.35295827e-01,  5.27644853e-01],
       [ 2.35044910e-02, -1.29719997e-01],
       [ 6.49027235e-01,  7.90590793e-01],
       [ 7.62758643e-01,  3.96171883e-01],
       [ 4.21564419e-01,  6.59117823e-01],
       [ 7.05892939e-01,  9.22063763e-01],
       [ 5.35295827e-01,  2.64698913e-01],
       [ 8.19624347e-01,  1.05353673e+00],
       [ 4.21564419e-01,  5.27644853e-01],
       [-1.

In [8]:
x_test

array([[ 0.76275864,  1.57942861],
       [ 0.1372359 , -0.26119297],
       [-1.3412724 , -1.31297673],
       [ 1.44514709,  0.79059079],
       [-1.2844067 , -1.31297673],
       [ 1.27454998,  1.71090158],
       [-1.39813811, -1.18150376],
       [ 0.53529583,  0.39617188],
       [ 0.59216153,  0.26469891],
       [ 0.1372359 ,  0.13322594],
       [ 1.04708716,  0.26469891],
       [ 0.42156442,  0.39617188],
       [ 0.53529583,  0.00175297],
       [ 0.47843012,  0.39617188],
       [ 0.53529583,  0.26469891],
       [-1.2844067 , -1.4444497 ],
       [ 0.42156442,  0.39617188],
       [ 0.36469871,  0.00175297],
       [-1.3412724 , -1.18150376],
       [-1.39813811, -1.05003079],
       [ 0.64902723,  1.05353673],
       [ 0.42156442,  0.39617188],
       [-1.05694388, -1.31297673],
       [-1.3412724 , -1.31297673],
       [ 0.59216153,  0.79059079],
       [-1.56873522, -1.31297673],
       [-1.05694388, -1.05003079],
       [ 0.30783301,  0.13322594],
       [-0.26082403,

In [9]:
x_test.shape

(38, 2)

In [10]:
x_train.shape

(112, 2)

In [11]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)


from sklearn.neighbors import KNeighborsClassifier
classifier1=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier1.fit(x_train,y_train)

from sklearn.svm import SVC
classifier2=SVC(kernel='linear',random_state=0)
classifier2.fit(x_train,y_train)

from sklearn.naive_bayes import GaussianNB
classifier3=GaussianNB()
classifier3.fit(x_train,y_train)

from sklearn.tree import DecisionTreeClassifier
classifier4=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier4.fit(x_train,y_train)

from sklearn.ensemble import RandomForestClassifier
classifier5=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier5.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [12]:
y_pred=classifier.predict(x_test)
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [13]:
y_pred1=classifier.predict(x_test)
y_pred1

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [14]:
y_pred2=classifier2.predict(x_test)
y_pred3=classifier3.predict(x_test)
y_pred4=classifier4.predict(x_test)
y_pred5=classifier5.predict(x_test)

In [15]:
y_test

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor'], dtype=object)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  1,  8]], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)



0.9473684210526315

In [18]:
accuracy_score(y_test,y_pred1)

0.9473684210526315

In [27]:
accuracy_score(y_test,y_pred2)

0.9736842105263158

In [28]:
accuracy_score(y_test,y_pred3)

0.9736842105263158

In [29]:
accuracy_score(y_test,y_pred4)

0.9473684210526315

In [30]:
accuracy_score(y_test,y_pred5)

0.9736842105263158

In [19]:
# model_train.py
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pickle

# Load data
iris = load_iris()
X, y = iris.data, iris.target
model = RandomForestClassifier()
model.fit(X, y)

# Save model
with open("model.pkl", "wb") as f:
    pickle.dump((model, iris.target_names), f)

print("Model saved as model.pkl")


Model saved as model.pkl
